### ISSUE TITLE
Update to be compatible with Moodle 3.0

### ISSUE THREAD

**Issue by joaocc** [moodleou/moodle-qbehaviour_opaque#3]
Hi,
Do you have any plans to update the plugin to become compatible with Moodle 3.0?
It would be great to be able to install it directly from moodle plugin directory (currently listed as compat with 2.9).
Thx

**Comment by timhunt** [comment]
Yes. I plan to do it. I checked all my plugins before Christmas, and something was wrong with the Opaque ones. I don't remember what was wrong until I get back to the office and check my notes. (I have been on holiday since Christmas.)

**Comment by joaocc** [comment]
Thank you!
